User.create(username: "derrick", email: "derrick@derrick.com", password: "123", password_confirmation: "123")
User.create(username: "justin", email: "gabalicious113@gmail.com", password: "123", password_confirmation: "123")
User.create(username: "ivan", email: "ivan@ivan.com", password: "123", password_confirmation: "123")
User.create(username: "david", email: "david@david.com", password: "123", password_confirmation: "123")
Survey.create(title: "Best Cat Survey", user_id: 1)
Survey.create(title: "Best Reptile Survey", user_id: 2)
Survey.create(title: "Best Dog Survey", user_id: 3)
Survey.create(title: "Best Bird Survey", user_id: 4)

Question.create(survey_id: 1, title: "What is the best Cat?")
Question.create(survey_id: 2, title: "What is the best Reptile?")
Question.create(survey_id: 3, title: "What is the best Dog?")
Question.create(survey_id: 4, title: "What is the best Bird?")

PossibleChoice.create(question_id: 1, content: "Black Cat", survey_id: 1)
PossibleChoice.create(question_id: 1, content: "Green Cat", survey_id: 1)
PossibleChoice.create(question_id: 2, content: "Aligator", survey_id: 2)
PossibleChoice.create(question_id: 2, content: "Dragon", survey_id: 2)
PossibleChoice.create(question_id: 3, content: "Shitsui", survey_id: 3)
PossibleChoice.create(question_id: 3, content: "Huski", survey_id: 3)
PossibleChoice.create(question_id: 4, content: "Parrot", survey_id: 4)
PossibleChoice.create(question_id: 4, content: "Humming Bird", survey_id: 4)
